server:
  port: 9999

spring:
 application:
   name: gateway-server

 cloud:
   gateway:
     discovery:
         locator:
         # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
#          lower-case-service-id: true #服务路由名小写
     routes:
       # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
       - id: payment_routh
         # 匹配后提供服务的路由地址
         uri: lb://eureka-provider-payment
         # 断言，路径相匹配的进行路由
         predicates:
           - Path=/**


eureka:
  client:
    #配置地址
    service-url:
      defaultZone: http://localhost:8888/eureka


